packagekit: Fix incorrect include path for 'gdesktop-enums.h'
This works currently without the fix, since '/usr/include/' is
included by default in search path. But this will break as shown
below, if 'gsettings-desktop-schemas' is installed in a non-standard
location.

../plugins/packagekit/gs-plugin-packagekit.c:16:10: fatal error: gdesktop-enums.h: No such file or directory
   16 | #include <gdesktop-enums.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.

Refer: https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/1370