trivial: Do not use a label that has not been defined
Otherwise we break the build:

../../src/gs-screenshot-image.c: In function 'gs_screenshot_image_complete_cb':
../../src/gs-screenshot-image.c:237:3: error: label 'out' used but not defined
   goto out;
   ^