gs-plugin-types: Declare GsPluginRefineFlags with unsigned number
A result of a shift by the 31 bits of a signed integer is undefined,
thus declare the number one as unsigned instead.

This covers a cppcheck report:

Error: CPPCHECK_WARNING (CWE-758): [#def1]
gnome-software-48.1/lib/gs-plugin-types.h:169: error[shiftTooManyBitsSigned]: Shifting signed 32-bit value by 31 bits is undefined behaviour
  167|   	GS_PLUGIN_REFINE_FLAGS_REQUIRE_DEVELOPER_NAME	= 1 << 29,
  168|   	GS_PLUGIN_REFINE_FLAGS_REQUIRE_KUDOS		= 1 << 30,
  169|-> 	GS_PLUGIN_REFINE_FLAGS_REQUIRE_CONTENT_RATING	= 1 << 31,
  170|   	GS_PLUGIN_REFINE_FLAGS_MASK			= ~0,
  171|   } GsPluginRefineFlags;

from https://svashisht.fedorapeople.org/openscanhub/mass-scans/f43-25-Apr-2025/gnome-software-48.1-1.fc43/scan-results.html